import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const products = [
  {
    slug: "tom-ford-oud-wood",
    name: "Oud Wood",
    brand: "Tom Ford",
    description: "A rich, woody fragrance with oud, sandalwood and vetiver. Sophisticated and long-lasting.",
    price: 245,
    compareAt: 280,
    stock: 12,
    images: '["/products/oud-wood-1.jpg","/products/oud-wood-2.jpg"]',
    family: "woody",
    occasion: "evening",
    intensity: "intense",
    gender: "unisex",
    tags: '["oud","woody","sandalwood","luxury"]',
    featured: true,
    isNew: false,
    onSale: true,
  },
  {
    slug: "creed-aventus",
    name: "Aventus",
    brand: "Creed",
    description: "Legendary pineapple and birch fragrance. Bold, confident, iconic.",
    price: 395,
    compareAt: null,
    stock: 8,
    images: '["/products/aventus-1.jpg"]',
    family: "fresh",
    occasion: "office",
    intensity: "moderate",
    gender: "masculine",
    tags: '["pineapple","smoky","citrus","iconic"]',
    featured: true,
    isNew: false,
    onSale: false,
  },
  {
    slug: "dior-sauvage-edt",
    name: "Sauvage Eau de Toilette",
    brand: "Dior",
    description: "Fresh, spicy, and magnetic. Pepper, bergamot and ambroxan.",
    price: 98,
    compareAt: 115,
    stock: 25,
    images: '["/products/sauvage-1.jpg"]',
    family: "fresh",
    occasion: "casual",
    intensity: "moderate",
    gender: "masculine",
    tags: '["fresh","spicy","bergamot","popular"]',
    featured: true,
    isNew: false,
    onSale: true,
  },
  {
    slug: "chanel-bleu-de-chanel",
    name: "Bleu de Chanel",
    brand: "Chanel",
    description: "A timeless woody-aromatic. Citrus, cedar and sandalwood.",
    price: 125,
    compareAt: null,
    stock: 18,
    images: '["/products/bleu-1.jpg"]',
    family: "fresh",
    occasion: "office",
    intensity: "moderate",
    gender: "masculine",
    tags: '["citrus","woody","versatile","elegant"]',
    featured: false,
    isNew: false,
    onSale: false,
  },
  {
    slug: "byredo-bal-d-afrique",
    name: "Bal d'Afrique",
    brand: "Byredo",
    description: "Sunny African marigold and vetiver. Warm, radiant, joyful.",
    price: 185,
    compareAt: null,
    stock: 10,
    images: '["/products/bal-afrique-1.jpg"]',
    family: "floral",
    occasion: "casual",
    intensity: "moderate",
    gender: "unisex",
    tags: '["floral","vetiver","warm","unique"]',
    featured: true,
    isNew: true,
    onSale: false,
  },
  {
    slug: "le-labo-santal-33",
    name: "Santal 33",
    brand: "Le Labo",
    description: "The cult sandalwood. Cardamom, iris, violet, and musky woods.",
    price: 192,
    compareAt: null,
    stock: 14,
    images: '["/products/santal33-1.jpg"]',
    family: "woody",
    occasion: "casual",
    intensity: "moderate",
    gender: "unisex",
    tags: '["sandalwood","woody","cardamom","cult"]',
    featured: true,
    isNew: false,
    onSale: false,
  },
  {
    slug: "acqua-di-parma-colonia",
    name: "Colonia",
    brand: "Acqua di Parma",
    description: "Classic Italian cologne. Sicilian citrus and Mediterranean herbs.",
    price: 135,
    compareAt: 150,
    stock: 20,
    images: '["/products/colonia-1.jpg"]',
    family: "fresh",
    occasion: "casual",
    intensity: "light",
    gender: "unisex",
    tags: '["citrus","fresh","classic","italian"]',
    featured: false,
    isNew: false,
    onSale: true,
  },
  {
    slug: "mfk-baccarat-rouge-540",
    name: "Baccarat Rouge 540",
    brand: "Maison Francis Kurkdjian",
    description: "Saffron, jasmine, amber. The red crystal of perfumery.",
    price: 325,
    compareAt: null,
    stock: 6,
    images: '["/products/br540-1.jpg"]',
    family: "oriental",
    occasion: "evening",
    intensity: "intense",
    gender: "unisex",
    tags: '["amber","saffron","jasmine","luxury"]',
    featured: true,
    isNew: false,
    onSale: false,
  },
  {
    slug: "prada-lhomme",
    name: "L'Homme",
    brand: "Prada",
    description: "Iris and amber. Clean, modern, refined.",
    price: 95,
    compareAt: null,
    stock: 22,
    images: '["/products/lhomme-1.jpg"]',
    family: "fresh",
    occasion: "office",
    intensity: "light",
    gender: "masculine",
    tags: '["iris","amber","clean","modern"]',
    featured: false,
    isNew: false,
    onSale: false,
  },
  {
    slug: "nishane-hacivat",
    name: "Hacivat",
    brand: "Nishane",
    description: "Pineapple, oakmoss, patchouli. Aventus' sophisticated cousin.",
    price: 185,
    compareAt: 210,
    stock: 9,
    images: '["/products/hacivat-1.jpg"]',
    family: "woody",
    occasion: "office",
    intensity: "intense",
    gender: "masculine",
    tags: '["pineapple","oakmoss","woody","niche"]',
    featured: true,
    isNew: false,
    onSale: true,
  },
  {
    slug: "diptyque-philosykos",
    name: "Philosykos",
    brand: "Diptyque",
    description: "Fig tree in a bottle. Green fig, fig wood, fig leaf.",
    price: 165,
    compareAt: null,
    stock: 11,
    images: '["/products/philosykos-1.jpg"]',
    family: "fresh",
    occasion: "casual",
    intensity: "light",
    gender: "unisex",
    tags: '["fig","green","natural","artistic"]',
    featured: false,
    isNew: true,
    onSale: false,
  },
  {
    slug: "ysl-black-opium",
    name: "Black Opium",
    brand: "Yves Saint Laurent",
    description: "Coffee, vanilla, white flowers. Addictive and bold.",
    price: 118,
    compareAt: null,
    stock: 16,
    images: '["/products/black-opium-1.jpg"]',
    family: "oriental",
    occasion: "evening",
    intensity: "intense",
    gender: "feminine",
    tags: '["coffee","vanilla","floral","bold"]',
    featured: false,
    isNew: false,
    onSale: false,
  },
  {
    slug: "hermes-terre-dhermes",
    name: "Terre d'Hermès",
    brand: "Hermès",
    description: "Grapefruit, pepper, vetiver. Earthy and refined.",
    price: 115,
    compareAt: 130,
    stock: 19,
    images: '["/products/terre-1.jpg"]',
    family: "woody",
    occasion: "office",
    intensity: "moderate",
    gender: "masculine",
    tags: '["citrus","vetiver","earthy","sophisticated"]',
    featured: false,
    isNew: false,
    onSale: true,
  },
  {
    slug: "amouage-interlude-man",
    name: "Interlude Man",
    brand: "Amouage",
    description: "Incense, oud, leather. Epic and opulent.",
    price: 285,
    compareAt: null,
    stock: 5,
    images: '["/products/interlude-1.jpg"]',
    family: "oriental",
    occasion: "evening",
    intensity: "intense",
    gender: "masculine",
    tags: '["incense","oud","leather","opulent"]',
    featured: true,
    isNew: false,
    onSale: false,
  },
  {
    slug: "jo-malone-wood-sage-sea-salt",
    name: "Wood Sage & Sea Salt",
    brand: "Jo Malone",
    description: "Coastal breeze, sage, grapefruit. Fresh and natural.",
    price: 78,
    compareAt: null,
    stock: 24,
    images: '["/products/wood-sage-1.jpg"]',
    family: "fresh",
    occasion: "casual",
    intensity: "light",
    gender: "unisex",
    tags: '["fresh","sage","citrus","natural"]',
    featured: false,
    isNew: false,
    onSale: false,
  },
  {
    slug: "xerjoff-naxos",
    name: "Naxos",
    brand: "Xerjoff",
    description: "Lavender, honey, tobacco. Mediterranean warmth.",
    price: 225,
    compareAt: null,
    stock: 7,
    images: '["/products/naxos-1.jpg"]',
    family: "oriental",
    occasion: "evening",
    intensity: "moderate",
    gender: "masculine",
    tags: '["lavender","tobacco","honey","mediterranean"]',
    featured: false,
    isNew: true,
    onSale: false,
  },
  {
    slug: "gucci-flora",
    name: "Flora",
    brand: "Gucci",
    description: "Gardenia, peony, rose. Romantic and feminine.",
    price: 92,
    compareAt: 105,
    stock: 21,
    images: '["/products/flora-1.jpg"]',
    family: "floral",
    occasion: "casual",
    intensity: "moderate",
    gender: "feminine",
    tags: '["floral","gardenia","romantic","feminine"]',
    featured: false,
    isNew: false,
    onSale: true,
  },
  {
    slug: "frederic-malle-portrait-of-a-lady",
    name: "Portrait of a Lady",
    brand: "Frédéric Malle",
    description: "Rose, patchouli, incense. A masterpiece of modern perfumery.",
    price: 295,
    compareAt: null,
    stock: 4,
    images: '["/products/portrait-1.jpg"]',
    family: "floral",
    occasion: "evening",
    intensity: "intense",
    gender: "feminine",
    tags: '["rose","patchouli","incense","masterpiece"]',
    featured: true,
    isNew: false,
    onSale: false,
  },
  {
    slug: "versace-eros",
    name: "Eros",
    brand: "Versace",
    description: "Mint, lemon, vanilla. Seductive and energetic.",
    price: 88,
    compareAt: null,
    stock: 28,
    images: '["/products/eros-1.jpg"]',
    family: "fresh",
    occasion: "casual",
    intensity: "moderate",
    gender: "masculine",
    tags: '["mint","vanilla","fresh","seductive"]',
    featured: false,
    isNew: false,
    onSale: false,
  },
  {
    slug: "penhaligons-blenheim-bouquet",
    name: "Blenheim Bouquet",
    brand: "Penhaligon's",
    description: "Lemon, lavender, pine. British elegance since 1902.",
    price: 145,
    compareAt: null,
    stock: 13,
    images: '["/products/blenheim-1.jpg"]',
    family: "fresh",
    occasion: "office",
    intensity: "light",
    gender: "masculine",
    tags: '["citrus","lavender","classic","british"]',
    featured: false,
    isNew: false,
    onSale: false,
  },
  {
    slug: "lartisan-parfumeur-passage-denfer",
    name: "Passage d'Enfer",
    brand: "L'Artisan Parfumeur",
    description: "Lily, incense, aloeswood. Mystical and contemplative.",
    price: 135,
    compareAt: null,
    stock: 8,
    images: '["/products/passage-1.jpg"]',
    family: "oriental",
    occasion: "evening",
    intensity: "moderate",
    gender: "unisex",
    tags: '["incense","lily","mystical","artistic"]',
    featured: false,
    isNew: true,
    onSale: false,
  },
  {
    slug: "dolce-gabbana-light-blue",
    name: "Light Blue",
    brand: "Dolce & Gabbana",
    description: "Apple, cedar, musk. Mediterranean summer in a bottle.",
    price: 85,
    compareAt: 95,
    stock: 30,
    images: '["/products/light-blue-1.jpg"]',
    family: "fresh",
    occasion: "casual",
    intensity: "light",
    gender: "feminine",
    tags: '["fresh","citrus","summer","popular"]',
    featured: false,
    isNew: false,
    onSale: true,
  },
  {
    slug: "kilian-black-phantom",
    name: "Black Phantom",
    brand: "Kilian",
    description: "Rum, coffee, caramel. Dark and addictive.",
    price: 275,
    compareAt: null,
    stock: 6,
    images: '["/products/black-phantom-1.jpg"]',
    family: "oriental",
    occasion: "evening",
    intensity: "intense",
    gender: "unisex",
    tags: '["rum","coffee","caramel","dark"]',
    featured: true,
    isNew: false,
    onSale: false,
  },
  {
    slug: "montblanc-explorer",
    name: "Explorer",
    brand: "Montblanc",
    description: "Bergamot, leather, ambroxan. Affordable luxury.",
    price: 72,
    compareAt: null,
    stock: 26,
    images: '["/products/explorer-1.jpg"]',
    family: "fresh",
    occasion: "office",
    intensity: "moderate",
    gender: "masculine",
    tags: '["fresh","leather","versatile","affordable"]',
    featured: false,
    isNew: false,
    onSale: false,
  },
  {
    slug: "serge-lutens-chergui",
    name: "Chergui",
    brand: "Serge Lutens",
    description: "Tobacco, honey, iris. Warm and exotic.",
    price: 165,
    compareAt: null,
    stock: 9,
    images: '["/products/chergui-1.jpg"]',
    family: "oriental",
    occasion: "evening",
    intensity: "intense",
    gender: "unisex",
    tags: '["tobacco","honey","iris","exotic"]',
    featured: false,
    isNew: false,
    onSale: false,
  },
  {
    slug: "acqua-di-gio-profumo",
    name: "Acqua di Gio Profumo",
    brand: "Giorgio Armani",
    description: "Bergamot, incense, patchouli. Aquatic depth.",
    price: 108,
    compareAt: 120,
    stock: 15,
    images: '["/products/profumo-1.jpg"]',
    family: "fresh",
    occasion: "office",
    intensity: "moderate",
    gender: "masculine",
    tags: '["aquatic","incense","fresh","refined"]',
    featured: false,
    isNew: false,
    onSale: true,
  },
];

const newsItems = [
  { title: "Tom Ford lanza Oud Wood Intense", brand: "Tom Ford", category: "designer", sourceName: "Fragrantica", sourceUrl: "https://www.fragrantica.com", publishedAt: new Date("2025-02-20T10:00:00Z"), imageUrl: null, excerpt: "La nueva intensificación del clásico Oud Wood llega con notas más profundas de oud y sándalo." },
  { title: "Nishane Hacivat X: edición limitada", brand: "Nishane", category: "niche", sourceName: "Basenotes", sourceUrl: "https://www.basenotes.net", publishedAt: new Date("2025-02-18T14:30:00Z"), imageUrl: null, excerpt: "La casa turca presenta una versión amplificada de su bestseller con piña y vetiver." },
  { title: "Ajmal perfumes de Oriente Medio", brand: "Ajmal", category: "arab", sourceName: "Parfumo", sourceUrl: "https://www.parfumo.com", publishedAt: new Date("2025-02-15T09:00:00Z"), imageUrl: null, excerpt: "Nueva colección de attars inspirados en las rutas del incienso." },
  { title: "Diptyque Orphéon: homenaje al cabaret", brand: "Diptyque", category: "niche", sourceName: "Fragrantica", sourceUrl: "https://www.fragrantica.com", publishedAt: new Date("2025-02-12T11:00:00Z"), imageUrl: null, excerpt: "Un perfume que evoca el París bohemio de los años 60." },
  { title: "Chanel N°5 L'Eau: reformulación 2025", brand: "Chanel", category: "designer", sourceName: "Basenotes", sourceUrl: "https://www.basenotes.net", publishedAt: new Date("2025-02-10T16:00:00Z"), imageUrl: null, excerpt: "La versión ligera del icono recibe un ajuste más verde y transparente." },
  { title: "Amouage Interlude Black Iris", brand: "Amouage", category: "arab", sourceName: "Parfumo", sourceUrl: "https://www.parfumo.com", publishedAt: new Date("2025-02-08T08:00:00Z"), imageUrl: null, excerpt: "La línea Interlude explora el iris en una interpretación oscura y resinosa." },
  { title: "Byredo Sundazed: verano eterno", brand: "Byredo", category: "niche", sourceName: "Fragrantica", sourceUrl: "https://www.fragrantica.com", publishedAt: new Date("2025-02-05T12:00:00Z"), imageUrl: null, excerpt: "Notas de algodón de azúcar y limón en un perfume solar y nostálgico." },
  { title: "Dior Sauvage Elixir Parfum", brand: "Dior", category: "designer", sourceName: "Basenotes", sourceUrl: "https://www.basenotes.net", publishedAt: new Date("2025-02-01T10:30:00Z"), imageUrl: null, excerpt: "La concentración más intensa de Sauvage con lavanda y regaliz." },
  { title: "Xerjoff Naxos: reedición en edición especial", brand: "Xerjoff", category: "niche", sourceName: "Parfumo", sourceUrl: "https://www.parfumo.com", publishedAt: new Date("2025-01-28T09:00:00Z"), imageUrl: null, excerpt: "El clásico mediterráneo vuelve en frasco de cristal tallado limitado." },
  { title: "Rasasi Hawas: éxito árabe en Occidente", brand: "Rasasi", category: "arab", sourceName: "Fragrantica", sourceUrl: "https://www.fragrantica.com", publishedAt: new Date("2025-01-25T14:00:00Z"), imageUrl: null, excerpt: "El ambroxán árabe conquista mercados europeos con su proyección legendaria." },
];

async function main() {
  console.log("Seeding database...");

  for (const p of products) {
    await prisma.product.upsert({
      where: { slug: p.slug },
      update: p,
      create: p,
    });
  }
  console.log(`Seeded ${products.length} products`);

  for (const n of newsItems) {
    await prisma.newsItem.create({ data: n });
  }
  console.log(`Seeded ${newsItems.length} news items`);

  console.log("Seed complete.");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
